openapi: 3.0.0
info:
  title: CineApp API
  description: API para gestionar la venta de entradas de cine y reservas.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo

paths:
  /api/peliculas:
    $ref: './paths/peliculas.yaml#/api/peliculas'
  /api/peliculas/{id}:
    $ref: './paths/peliculas.yaml#/api/peliculas/{id}'
  /api/salas:
    $ref: './paths/salas.yaml#/api/salas'
  /api/salas/{id}:
    $ref: './paths/salas.yaml#/api/salas/{id}'
  /api/funciones:
    $ref: './paths/funciones.yaml#/api/funciones'
  /api/funciones/{id}:
    $ref: './paths/funciones.yaml#/api/funciones/{id}'
  /api/clientes:
    $ref: './paths/clientes.yaml#/api/clientes'
  /api/clientes/{id}:
    $ref: './paths/clientes.yaml#/api/clientes/{id}'
  /api/reservas:
    $ref: './paths/reservas.yaml#/api/reservas'
  /api/reservas/{id}:
    $ref: './paths/reservas.yaml#/api/reservas/{id}'

components:
  schemas:
    $ref: './components/schemas.yaml#/schemas'